language: groovy

jdk:
- oraclejdk8

before_install:
- wget http://dl.bintray.com/groovy/maven/groovy-binary-2.3.7.zip -O /tmp/groovy.zip
- cd /tmp/ && unzip groovy.zip && cd -
- export GROOVY_HOME=/tmp/groovy-2.3.7
- alias groovy="${GROOVY_HOME}/bin/groovy"

script: ./runall.sh
